### ISSUE TITLE
Assertion Failed: A helper named 'panels.panel' could not be found

### ISSUE THREAD

**Issue by ravikarn** [adopted-ember-addons/ember-collapsible-panel#31]
I was trying to embed collapsible display using version ember-collapsible-panel-1.0.

After installing also, I am getting assertion fail issue.

"Error: Assertion Failed: A helper named 'p.toggle' could not be found
    at EmberError (http://localhost:4200/assets/vendor.js:25125:21)
    at Object._emberMetalCore.default.assert (http://localhost:4200/assets/vendor.js:14755:13)
    at Object.lookupHelper [as default] (http://localhost:4200/assets/vendor.js:20038:32)
    at Object.lookupHelperHook [as lookupHelper] (http://localhost:4200/assets/vendor.js:17778:55)
    at http://localhost:4200/assets/vendor.js:60155:30
    at Object.renderAndCleanup (http://localhost:4200/assets/vendor.js:61625:18)
    at hostBlock (http://localhost:4200/assets/vendor.js:60162:32)
    at continueBlock (http://localhost:4200/assets/vendor.js:60154:5)
    at Object.block (http://localhost:4200/assets/vendor.js:60150:5)
    at Object.block (http://localhost:4200/assets/vendor.js:59377:17)"

My hbs code is as sample provided in page.

{{#cp-panel open=true as |p|}}
  {{#p.toggle}}
    <p>Click me!</p>
  {{/p.toggle}}
  {{#p.body}}
    <div>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo repellendus nisi asperiores esse aperiam aliquid nulla ad dolor autem neque, nihil inventore temporibus delectus earum facere corporis, quam ipsum maxime.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus neque magnam, hic quis beatae repellendus harum modi pariatur minus quidem alias! Eius incidunt impedit eaque, est, illo officiis expedita molestiae.</p>
    </div>
  {{/p.body}}

{{/cp-panel}}

**Comment by brenna** [comment]
If you're using 1.0 you'll have to use the older (non-contextual components) API: 
```hbs
{{#cp-panel}}
  {{#cp-panel-toggle}}
    <p>Click me!</p>
  {{/cp-panel-toggle}}
  {{#cp-panel-body}}
    <div>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo repellendus nisi asperiores esse aperiam aliquid nulla ad dolor autem neque, nihil inventore temporibus delectus earum facere corporis, quam ipsum maxime.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus neque magnam, hic quis beatae repellendus harum modi pariatur minus quidem alias! Eius incidunt impedit eaque, est, illo officiis expedita molestiae.</p>
    </div>
  {{/cp-panel-body}}

{{/cp-panel}}
```

Further examples of the old API are available [here](https://github.com/tedconf/ember-collapsible-panel/tree/1eacd9ebb57a2bbd6825a1e855d968d08e2c81ae/tests/dummy/app/pods/demo)
